### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ColoredThoughts** [dramamine/leftovers-again#20]
After being asked " What programming language are you primarily using, the program crashes showing this error:

```
(node:8272) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CALLBACK]:
Callback must be a function
    at maybeCallback (fs.js:124:9)
    at Object.fs.writeFile (fs.js:1244:14)
    at writePackage (C:\Users\NoInfoStealing Zone\Documents\GitHub\Bot Poke\node
_modules\leftovers-again\scripts\generate.js:128:6)
    at inquirer.prompt.then (C:\Users\NoInfoStealing Zone\Documents\GitHub\Bot P
oke\node_modules\leftovers-again\scripts\generate.js:182:3)
(node:8272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 1)
(node:8272) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

```

How do I solve this?

**Comment by dramamine** [comment]
What are you using to run node?
I would use something like mingw32 (git bash). The default command line isn't super great for node things.

What version of node are you running?
