### ISSUE TITLE
-damage on Type: Null breaks

### ISSUE THREAD

**Issue by brandonhorst** [dramamine/leftovers-again#6]
I think this Pokemon was named explicitly to screw with javascript programmers.

The problem is handling this message: `|-damage|p1a: Type: Null|168/394`. Reproduce it like this:

```js
const BattleStore = require('leftovers-again/lib/model/battlestore').default
const store = new BattleStore()
store.handle('-damage', ['p1a: Type: Null', '168/394'])
```

Tracing it down, it looks like `PokeUtil:identWithoutPosition` fails because it does a split on the `:` character.

The error:

```
/Users/brandonhorst/Projects/showdown-bot/node_modules/leftovers-again/lib/model/battlestore.js:227
      move.prevhp = mon.hp;
                       ^

TypeError: Cannot read property 'hp' of undefined
    at BattleStore.handleDamage (/Users/brandonhorst/Projects/showdown-bot/node_modules/leftovers-again/lib/model/battlestore.js:227:24)
    at BattleStore.handle (/Users/brandonhorst/Projects/showdown-bot/node_modules/leftovers-again/lib/model/battlestore.js:107:29)
    at new Replay (/Users/brandonhorst/Projects/showdown-bot/index.js:128:11)
    at Request.request [as _callback] (/Users/brandonhorst/Projects/showdown-bot/index.js:272:19)
    at Request.self.callback (/Users/brandonhorst/Projects/showdown-bot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/brandonhorst/Projects/showdown-bot/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
```

**Comment by dramamine** [comment]
Huh. Do you mean somebody nicknamed a Pokemon "Type: Null"?! (i.e. any nickname with a colon will break?)

**Comment by brandonhorst** [comment]
Naw it's a real mon dude. The future is weird. http://bulbapedia.bulbagarden.net/wiki/Type:_Null_(Pok%C3%A9mon)

**Comment by brandonhorst** [comment]
You can test by loading up this replay: `gen7pokebankou-490839155`

**Comment by dramamine** [comment]
Thanks for the PR, does that fix all the issues you've seen with this 'mon?

**Comment by brandonhorst** [comment]
That seems to allow the `BattleStore` to process the entire `gen7pokebankou-490839155` replay, but there may well be other issues.

I'm using `BattleStore` to train a machine learning bot for a project I'm doing, so I'm eventually going to be processing a crapton of replays, so I'll probably be finding more bugs eventually.
